FROM python:3

RUN mkdir -p /usr/src/hourserents
WORKDIR /usr/src/hourserents

COPY requirements.txt /usr/src/hourserents/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY controllers /usr/src/hourserents/
COPY db /usr/src/hourserents/
COPY main.py boot.sh /usr/src/hourserents/
RUN chmod +x boot.sh

ARG ENV
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_PORT
ARG DATA_SERVER
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD

ENV FLASK_APP main.py

EXPOSE 5000

CMD python main.py
